name: Auto commit

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "0 14,6,21 * * 1-0" # See https://crontab.guru/#0_7,9,11_*_*_1,3

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: DEBUG 
        run: echo "::debug::Ref = ${{github.ref}}"
      - uses: actions/checkout@v3      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "nkflx2@gmail.com"
          git config --local user.name "ardakazanci"
          git add -A
          
          arr[0]="dombili(bot): 🥩 auto commit"
          arr[1]="dombili(bot): 🌯 auto commit"
          arr[2]="dombili(bot): 🍖 auto commit"
          arr[3]="dombili(bot): 🍕 auto commit"
          arr[4]="dombili(bot): 🍔 auto commit"
          arr[5]="dombili(bot): 🍟 auto commit"
          arr[6]="dombili(bot): 🥯 auto commit"
          arr[7]="dombili(bot): 🍩 auto commit"
          arr[8]="dombili(bot): 🥪 auto commit"
          arr[9]="dombili(bot): 🍫 auto commit"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
